import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs"
import "./globals.css";

import { SocketProvider } from "@/components/providers/socket-providers";
import { QueryProvider } from "@/components/providers/query-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from '../lib/utils';

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
  icons: {
    icon: "/src/app/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <head>
        <link  rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={cn(font.className,"bg-white dark:bg-[#313338]")}>
        {/* <Navbar /> */}
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem={false}
        storageKey="discord-theme"
        >
          <SocketProvider>
          <ModalProvider />
          <QueryProvider>
            {children}
          </QueryProvider>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
